version: "1.0"

stages:
  - wait
  - retrigger

steps:
  wait:
    stage: wait
    title: Wait
    type: freestyle
    image: denoland/deno:alpine
    fail_fast: false
    commands:
      - |-
        deno eval --ext=js "
        setInterval(() => {
          console.log(Math.random().toString(2))
        }, 100);

        const delay = Math.floor((Math.random() + 2) * 60 * 1000); // 2–3 minutes
        setTimeout(() => {
          console.log('🔵\n\tThe Matrix is everywhere.\n\tIt is all around us.\n🔴')
          Deno.exit(0);
        }, delay);
        "

  codefresh-run:
    stage: retrigger
    title: Run again
    type: codefresh-run
    arguments:
      PIPELINE_ID: ${{CF_PIPELINE_NAME}}
      DETACH: true
      VARIABLE:
        - key1=val1
