version: "1.0"

stages:
  - wait
  - retrigger

steps:
  wait:
    stage: wait
    title: Wait
    type: freestyle
    image: quay.io/codefresh/sandbox/deno:alpine
    fail_fast: false
    commands:
      - |-
        deno eval --ext=js "
        setInterval(() => {
          console.log(Math.random().toString(2))
        }, 100);

        const delay = Math.floor((Math.random() + 2) * 60 * 1000); // 2–3 minutes
        setTimeout(() => {
          console.log('🔵\n\tThe Matrix is everywhere.\n\tIt is all around us.\n🔴')
          Deno.exit(0);
        }, delay);
        "

  run:
    stage: retrigger
    title: Run again
    image: quay.io/codefresh/sandbox/deno:alpine
    commands:
      - |-
        deno eval --ext=js "
        const [apiKey, pipelineName, runtime] = Deno.args;
        console.log('🚀  Running pipeline “' + pipelineName + '” on “' + (runtime ? runtime : '[pipeline settings]') +'”');
        const resp = await fetch(
          new URL(
            encodeURIComponent(pipelineName),
            'https://g.codefresh.io/api/pipelines/run/',
          ),
          {
            method: 'POST',
            headers: {
              'Authorization': apiKey,
              'Content-Type': 'application/json',
            },
            body: runtime
              ? JSON.stringify({
                userMachineConfig: { runtimeName: runtime },
                variables: { RUNTIME: runtime },
              })
              : null,
          },
        );
        console.log(await resp.text());
        if (!resp.ok) {
          Deno.exit(1);
        }
        " $CF_API_KEY $CF_PIPELINE_NAME $RUNTIME
